// SPDX-FileCopyrightText: 2026 PuroSlavKing <puroslavking@yahoo.com>
//
// SPDX-License-Identifier: AGPL-3.0-or-later

using System.Globalization;
using Content.Client.Administration.Managers;
using Content.Shared.Localizations;
using Robust.Client.AutoGenerated;
using Robust.Client.UserInterface.CustomControls;
using Robust.Client.UserInterface.XAML;

namespace Content.Client.Options.UI
{
    [GenerateTypedNameReferences]
    public sealed partial class OptionsMenu : DefaultWindow
    {
        [Dependency] private IClientAdminManager _adminManager = default!;
        [Dependency] private ContentLocalizationManager _contentLoc = default!; // Orion

        public OptionsMenu()
        {
            RobustXamlLoader.Load(this);
            IoCManager.InjectDependencies(this);

            // Orion-Start
            _contentLoc.CultureChanged += OnCultureChanged;
            UpdateLocalizedText();
            // Orion-End
            UpdateTabs(); // Orion-Edit: Moved here
        } // Orion-Edit: Separate tabs

        // Orion-Start
        private void OnCultureChanged(CultureInfo culture)
        {
            UpdateLocalizedText();
        }
        // Orion-End

        // Orion-Edit-Start: Separate from OptionsMenu
        private void UpdateLocalizedText()
        {
            Title = Loc.GetString("ui-options-title"); // Orion
            Tabs.SetTabTitle(0, Loc.GetString("ui-options-tab-misc"));
            Tabs.SetTabTitle(1, Loc.GetString("ui-options-tab-graphics"));
            Tabs.SetTabTitle(2, Loc.GetString("ui-options-tab-controls"));
            Tabs.SetTabTitle(3, Loc.GetString("ui-options-tab-audio"));
            Tabs.SetTabTitle(4, Loc.GetString("ui-options-tab-accessibility"));
            Tabs.SetTabTitle(5, Loc.GetString("ui-options-tab-admin"));
            MiscTab.UpdateLocalizedText(); // Orion
        }
        // Orion-Edit-End

        // Orion-Start
        protected override void Dispose(bool disposing)
        {
            _contentLoc.CultureChanged -= OnCultureChanged;
            base.Dispose(disposing);
        }
        // Orion-End

        public void UpdateTabs()
        {
            var isAdmin = _adminManager.IsAdmin(true);
            Tabs.SetTabVisible(5, isAdmin);

            GraphicsTab.Control.ReloadValues();
            MiscTab.Control.ReloadValues();
            AccessibilityTab.Control.ReloadValues();
            AudioTab.Control.ReloadValues();
            AdminOptionsTab.Control.ReloadValues();
        }
    }
}
