using Content.Client.UserInterface.Controls;
using Robust.Client.AutoGenerated;
using Robust.Client.UserInterface;
using Robust.Client.UserInterface.XAML;
using Robust.Shared.Utility;

namespace Content.Client._Orion.Research.UI;

[GenerateTypedNameReferences]
public sealed partial class OrionResearchConsoleLogWindow : FancyWindow
{
    public OrionResearchConsoleLogWindow()
    {
        RobustXamlLoader.Load(this);
    }

    public void SetExperimentEntries(IEnumerable<Control> entries)
    {
        ExperimentsContainer.RemoveAllChildren();
        foreach (var entry in entries)
            ExperimentsContainer.AddChild(entry);
    }

    public void SetLogs(FormattedMessage message)
    {
        LogsLabel.SetMessage(message);
    }
}
