using System.Linq;
using System.Numerics;
using Content.Client.Research;
using Content.Client.UserInterface.Controls;
using Content.Common.Research;
using Content.Shared._Orion.Research;
using Content.Shared._Orion.Research.Prototypes;
using Content.Shared.Research.Components;
using Content.Shared.Research.Prototypes;
using Robust.Client.AutoGenerated;
using Robust.Client.GameObjects;
using Robust.Client.Graphics;
using Robust.Client.UserInterface;
using Robust.Client.UserInterface.Controls;
using Robust.Client.UserInterface.XAML;
using Robust.Shared.IoC;
using Robust.Shared.Prototypes;
using Robust.Shared.Utility;

namespace Content.Client._Orion.Research.UI;

[GenerateTypedNameReferences]
public sealed partial class OrionResearchConsoleMenu : FancyWindow
{
    public event Action<string>? TechnologyRequested;
    public event Action? ServerSelectionRequested;

    [Dependency] private readonly IEntityManager _entity = default!;
    [Dependency] private readonly IPrototypeManager _prototypes = default!;
    [Dependency] private readonly ILocalizationManager _localization = default!;

    private readonly ResearchSystem _research;
    private readonly SpriteSystem _sprite;
    private OrionResearchConsoleLogWindow? _journal;
    private ResearchConsoleBoundInterfaceState? _state;
    private EntityUid _owner;
    private string? _selectedTechnology;

    public OrionResearchConsoleMenu()
    {
        RobustXamlLoader.Load(this);
        IoCManager.InjectDependencies(this);
        _research = _entity.System<ResearchSystem>();
        _sprite = _entity.System<SpriteSystem>();

        ServerButton.OnPressed += _ => ServerSelectionRequested?.Invoke();
        JournalButton.OnPressed += _ => ToggleJournal();
        RecenterButton.OnPressed += _ => ResearchGraph.Recenter();
        ResearchGraph.TechnologySelected += SelectTechnology;
    }

    public void SetEntity(EntityUid owner)
    {
        _owner = owner;
    }

    public void UpdateState(ResearchConsoleBoundInterfaceState state)
    {
        _state = state;
        ResearchGraph.SetTechnologies(state.Researches);
        UpdateHeader(state);
        UpdateJournal(state);

        if (_selectedTechnology != null &&
            state.Researches.TryGetValue(_selectedTechnology, out var availability) &&
            _prototypes.TryIndex<TechnologyPrototype>(_selectedTechnology, out var technology))
            SelectTechnology(technology, availability);
        else
            ShowOverview(state);
    }

    private void UpdateHeader(ResearchConsoleBoundInterfaceState state)
    {
        var balances = new FormattedMessage();
        var network = string.IsNullOrWhiteSpace(state.NetworkId)
            ? Loc.GetString("research-machine-common-none")
            : FormattedMessage.EscapeText(state.NetworkId);
        balances.AddMarkupOrThrow($"[bold]{Loc.GetString("research-console-network-label")}[/bold] {network}");

        foreach (var point in state.PointBalances)
        {
            balances.PushNewline();
            balances.AddMarkupOrThrow($"[color=lightgreen]{FormattedMessage.EscapeText(LocalizePointType(point.Type))}[/color]: {point.Amount}");
        }
        ResearchAmountLabel.SetMessage(balances);

        var experimentSummary = new FormattedMessage();
        var active = state.Experiments.Count(x => x.State == ResearchExperimentState.Active);
        var completed = state.Experiments.Count(x => x.State == ResearchExperimentState.Completed);
        experimentSummary.AddMarkupOrThrow(Loc.GetString("research-console-experiment-summary", ("active", active), ("completed", completed)));
        ExperimentsLabel.SetMessage(experimentSummary);

        TierDisplayContainer.RemoveAllChildren();
        if (!_entity.TryGetComponent<TechnologyDatabaseComponent>(_owner, out var database))
            return;

        foreach (var disciplineId in database.SupportedDisciplines)
        {
            if (!_prototypes.TryIndex(disciplineId, out TechDisciplinePrototype? discipline))
                continue;

            var total = _prototypes.EnumeratePrototypes<TechnologyPrototype>()
                .Count(x => x.Discipline == discipline.ID && !x.Hidden);
            var researched = state.ResearchedTechnologies.Count(id =>
                _prototypes.TryIndex(id, out TechnologyPrototype? technology) &&
                technology.Discipline == discipline.ID && !technology.Hidden);
            var percent = total == 0 ? 0 : (int) MathF.Round(researched / (float) total * 100f);

            var texture = new TextureRect
            {
                Texture = _sprite.Frame0(discipline.Icon),
                TextureScale = new Vector2(2, 2),
                VerticalAlignment = VAlignment.Center,
            };
            var label = new Label { Text = $"{Loc.GetString(discipline.Name)}: {percent}%" };
            TierDisplayContainer.AddChild(new BoxContainer
            {
                Orientation = BoxContainer.LayoutOrientation.Horizontal,
                Margin = new Thickness(0, 0, 12, 0),
                Children = { texture, label },
            });
        }
    }

    private void ShowOverview(ResearchConsoleBoundInterfaceState state)
    {
        InfoContainer.RemoveAllChildren();
        InfoContainer.AddChild(new Label
        {
            Text = Loc.GetString("research-console-select-technology"),
            HorizontalAlignment = HAlignment.Center,
        });

        var visible = state.VisibleTechnologies.Count;
        var researched = state.ResearchedTechnologies.Count;
        var available = state.AvailableTechnologies.Count;
        InfoContainer.AddChild(new Label
        {
            Text = Loc.GetString("research-console-overview-counts", ("visible", visible), ("available", available), ("researched", researched)),
            ClipText = false,
        });
    }

    private void SelectTechnology(TechnologyPrototype technology, ResearchAvailability availability)
    {
        _selectedTechnology = technology.ID;
        InfoContainer.RemoveAllChildren();

        var header = new BoxContainer
        {
            Orientation = BoxContainer.LayoutOrientation.Horizontal,
            SeparationOverride = 8,
        };
        header.AddChild(new TextureRect
        {
            Texture = _sprite.Frame0(technology.Icon),
            SetSize = new Vector2(64, 64),
            Stretch = TextureRect.StretchMode.KeepAspectCentered,
            TextureScale = new Vector2(2, 2),
        });
        header.AddChild(new Label
        {
            Text = Loc.GetString(technology.Name),
            StyleClasses = { "LabelKeyText" },
            ClipText = false,
            HorizontalExpand = true,
        });
        InfoContainer.AddChild(header);

        var description = new RichTextLabel { HorizontalExpand = true };
        description.SetMessage(_research.GetTechnologyDescription(technology, includeCost: false, includeTier: true, includePrereqs: false));
        InfoContainer.AddChild(description);

        var costs = new FormattedMessage();
        costs.AddMarkupOrThrow($"[bold]{Loc.GetString("research-console-tech-cost-title")}[/bold]");
        var pointCosts = technology.PointCosts.Count > 0
            ? technology.PointCosts
            : [new ResearchPointAmount { Type = "General", Amount = technology.Cost }];
        foreach (var cost in pointCosts)
        {
            costs.PushNewline();
            costs.AddMarkupOrThrow($"• [color=lightgreen]{FormattedMessage.EscapeText(LocalizePointType(cost.Type))}[/color]: {cost.Amount}");
        }
        var costLabel = new RichTextLabel();
        costLabel.SetMessage(costs);
        InfoContainer.AddChild(costLabel);

        var lockReason = _state?.TechnologyLockReasons.GetValueOrDefault(technology.ID) ?? ResearchTechnologyLockReason.None;
        if (technology.TechnologyPrerequisites.Count > 0)
        {
            InfoContainer.AddChild(new Label { Text = Loc.GetString("research-console-tech-required-technologies-title") });
            foreach (var prerequisiteId in technology.TechnologyPrerequisites)
            {
                if (!_prototypes.TryIndex(prerequisiteId, out TechnologyPrototype? prerequisite))
                    continue;
                var isDone = _state?.ResearchedTechnologies.Contains(prerequisiteId) == true;
                InfoContainer.AddChild(new Label
                {
                    Text = $"{(isDone ? "✓" : "✗")} {Loc.GetString(prerequisite.Name)}",
                    Modulate = isDone ? Color.LightGreen : Color.IndianRed,
                });
            }
        }

        if (technology.RequiredExperiments.Count > 0)
        {
            InfoContainer.AddChild(new Label { Text = Loc.GetString("research-console-tech-required-experiments-title") });
            foreach (var experimentId in technology.RequiredExperiments)
            {
                if (!_prototypes.TryIndex<ResearchExperimentPrototype>(experimentId, out var experiment))
                    continue;
                var isDone = _state?.CompletedExperiments.Contains(experimentId) == true;
                InfoContainer.AddChild(new Label
                {
                    Text = $"{(isDone ? "✓" : "✗")} {Loc.GetString(experiment.Name)}",
                    Modulate = isDone ? Color.LightGreen : Color.IndianRed,
                });
            }
        }

        InfoContainer.AddChild(new Label { Text = Loc.GetString("research-console-unlocks-text") });
        if (technology.RecipeUnlocks.Count == 0 && technology.GenericUnlocks.Count == 0)
            InfoContainer.AddChild(new Label { Text = Loc.GetString("research-console-tech-empty-unlocks"), Modulate = Color.Gray });
        else
        {
            foreach (var recipeId in technology.RecipeUnlocks)
                InfoContainer.AddChild(new Label { Text = $"• {recipeId}" });
            foreach (var generic in technology.GenericUnlocks)
                InfoContainer.AddChild(new Label { Text = $"• {Loc.GetString(generic.UnlockDescription)}" });
        }

        var buy = new Button
        {
            Text = Loc.GetString("research-console-menu-server-research-button"),
            Disabled = availability != ResearchAvailability.Available || lockReason != ResearchTechnologyLockReason.None,
            HorizontalAlignment = HAlignment.Left,
        };
        buy.OnPressed += _ => TechnologyRequested?.Invoke(technology.ID);
        InfoContainer.AddChild(buy);

        if (lockReason != ResearchTechnologyLockReason.None)
            InfoContainer.AddChild(new Label { Text = LocalizeLockReason(lockReason), Modulate = Color.IndianRed, ClipText = false });
    }

    private void ToggleJournal()
    {
        if (_journal == null)
        {
            _journal = new OrionResearchConsoleLogWindow();
            _journal.OnClose += () => _journal = null;
        }

        if (_journal.IsOpen)
            _journal.Close();
        else
            _journal.OpenCentered();

        if (_state != null)
            UpdateJournal(_state);
    }

    private void UpdateJournal(ResearchConsoleBoundInterfaceState state)
    {
        if (_journal == null)
            return;

        var experimentControls = new List<Control>();
        foreach (var data in state.Experiments)
        {
            if (!_prototypes.TryIndex<ResearchExperimentPrototype>(data.Id, out var experiment))
                continue;

            var stateText = data.State switch
            {
                ResearchExperimentState.Active => Loc.GetString("research-console-experiment-state-active"),
                ResearchExperimentState.Available => Loc.GetString("research-console-experiment-state-available"),
                ResearchExperimentState.Completed => Loc.GetString("research-console-experiment-state-completed"),
                ResearchExperimentState.Skipped => Loc.GetString("research-console-experiment-state-skipped"),
                _ => Loc.GetString("research-console-experiment-state-unavailable"),
            };

            experimentControls.Add(new Label
            {
                Text = $"[{stateText}] {Loc.GetString(experiment.Name)} — {data.Progress}/{data.Target}",
                ClipText = false,
            });
        }

        if (experimentControls.Count == 0)
            experimentControls.Add(new Label { Text = Loc.GetString("research-console-experiments-empty"), Modulate = Color.Gray });
        _journal.SetExperimentEntries(experimentControls);

        var logs = new FormattedMessage();
        foreach (var entry in state.Logs.TakeLast(50))
        {
            if (!logs.IsEmpty)
                logs.PushNewline();
            logs.AddMarkupOrThrow($"[color=gray]{FormattedMessage.EscapeText(LocalizeLogCategory(entry.Category))}[/color] ");
            logs.AddText(entry.Message);
        }
        if (logs.IsEmpty)
            logs.AddMarkupOrThrow($"[color=gray]{Loc.GetString("research-console-logs-empty")}[/color]");
        _journal.SetLogs(logs);
    }

    private string LocalizePointType(string type)
    {
        var key = $"research-point-type-{type.ToLowerInvariant()}";
        return _localization.TryGetString(key, out var localized) ? localized : type;
    }

    private string LocalizeLogCategory(string category)
    {
        var key = $"research-log-category-{category.Trim().Replace("_", "-").Replace(" ", "-").ToLowerInvariant()}";
        return _localization.TryGetString(key, out var localized) ? localized : category;
    }

    private string LocalizeLockReason(ResearchTechnologyLockReason reason)
    {
        var key = $"research-technology-lock-reason-{reason.ToString().ToLowerInvariant()}";
        return _localization.TryGetString(key, out var localized) ? localized : reason.ToString();
    }

    public override void Close()
    {
        _journal?.Close();
        _journal = null;
        base.Close();
    }
}
